export const bbConfig = {
  key: "bb",
  label: "Broadband",
  supportsSubprojects: false,
  fields: ["receiving_date", "ckt_id", "customer", "address", "city", "lc", "provider_id", "status"],
  uiFields: [
    { key: "receiving_date", label: "Receiving Date", listView: true, type: "date" },
    { key: "ckt_id", label: "Circuit ID", listView: true, type: "text" },
    { key: "customer", label: "Customer", listView: true, type: "text" },
    { key: "address", label: "Address", listView: false, type: "text" },
    { key: "city", label: "City", listView: true, type: "text" },
    { key: "lc", label: "LC", listView: false, type: "text" },
    { key: "status_key", label: "Status", listView: true, type: "badge" },
  ],
  detailSections: ["site", "tickets", "billing"],
  formFields: ["receiving_date", "ckt_id", "customer", "address", "city", "lc"],
  bulkColumns: [],
  statusColors: {},
  generateOptions: [],
  photoSequence: [],
}
