export const mcConfig = {
  key: "mc",
  label: "Mast CM",
  supportsSubprojects: true,
  fields: ["receiving_date", "ckt_id", "customer", "address", "state_id", "height", "audit_date", "mpaint", "mnbr", "arr", "ep", "ec", "cm_date", "status"],
  uiFields: [
    { key: "receiving_date", label: "Receiving Date", listView: true, type: "date" },
    { key: "ckt_id", label: "Circuit ID", listView: true, type: "text" },
    { key: "customer", label: "Customer", listView: true, type: "text" },
    { key: "address", label: "Address", listView: false, type: "text" },
    { key: "state_id", label: "State", listView: true, type: "select" },
    { key: "height", label: "Height (mtr)", listView: false, type: "number" },
    { key: "lc", label: "LC", listView: false, type: "text" },
    { key: "audit_date", label: "Audit Date", listView: false, type: "date" },
    { key: "mpaint", label: "Painting", listView: false, type: "bool" },
    { key: "mnbr", label: "Nut-Bolt Replacement", listView: false, type: "bool" },
    { key: "arr", label: "Lightning Arrester", listView: false, type: "bool" },
    { key: "ep", label: "Earthpit", listView: false, type: "bool" },
    { key: "ec", label: "Earthing Cable (mtr)", listView: false, type: "number" },
    { key: "cm_date", label: "CM Date", listView: false, type: "date" },
    { key: "status_key", label: "Status", listView: true, type: "badge" },
  ],
  detailSections: ["site", "photos", "transactions", "updates", "tickets", "billing"],
  formFields: ["receiving_date", "ckt_id", "customer", "address", "state_id", "height", "lc", "audit_date", "mpaint", "mnbr", "arr", "ep", "ec"],
  bulkColumns: ["ckt_id", "customer", "address", "state_id", "height", "lc", "audit_date", "mpaint", "mnbr", "arr", "ep", "ec"],
  statusColors: {},
  generateOptions: ["WCC", "Report"],
  photoSequence: ["FE in safety gear", "Foundation snap", "Full tower snap", "Top platform snap", "Earthing snap"],
}
