export const mdConfig = {
  key: "md",
  label: "Mast Dismantle",
  supportsSubprojects: true,
  fields: ["receiving_date", "ckt_id", "customer", "address", "state_id", "lc", "height", "visit_date", "outcome", "dismantle_date", "status"],
  uiFields: [
    { key: "receiving_date", label: "Receiving Date", listView: true, type: "date" },
    { key: "ckt_id", label: "Circuit ID", listView: true, type: "text" },
    { key: "customer", label: "Customer", listView: true, type: "text" },
    { key: "address", label: "Address", listView: false, type: "text" },
    { key: "state_id", label: "State", listView: true, type: "select" },
    { key: "height", label: "Height (mtr)", listView: false, type: "number" },
    { key: "lc", label: "LC", listView: false, type: "text" },
    { key: "visit_date", label: "Visit Date", listView: false, type: "date" },
    { key: "outcome", label: "Outcome", listView: false, type: "text" },
    { key: "dismantle_date", label: "Dismantle Date", listView: false, type: "date" },
    { key: "status_key", label: "Status", listView: true, type: "badge" },
  ],
  detailSections: ["site", "fe", "transactions", "updates", "tickets", "billing"],
  formFields: ["receiving_date", "ckt_id", "customer", "address", "state_id", "height"],
  bulkColumns: ["ckt_id", "customer", "address", "state_id", "height"],
  statusColors: {},
  generateOptions: ["WCC", "Tx Copy"],
  photoSequence: [],
}
