export const miConfig = {
  key: "mi",
  label: "Mast Installation",
  supportsSubprojects: false,
  fields: ["receiving_date", "ckt_id", "customer", "address", "city", "lc", "height", "permission_date", "edd", "status"],
  uiFields: [
    { key: "receiving_date", label: "Receiving Date", listView: true, type: "date" },
    { key: "ckt_id", label: "Circuit ID", listView: true, type: "text" },
    { key: "customer", label: "Customer", listView: true, type: "text" },
    { key: "address", label: "Address", listView: false, type: "text" },
    { key: "city", label: "City", listView: true, type: "text" },
    { key: "height", label: "Height (mtr)", listView: false, type: "number" },
    { key: "status_key", label: "Status", listView: true, type: "badge" },
  ],
  detailSections: ["site", "finance", "transactions", "updates", "billing"],
  formFields: ["receiving_date", "ckt_id", "customer", "address", "city", "height"],
  bulkColumns: ["ckt_id", "customer", "address", "city", "height"],
  statusColors: {},
  generateOptions: ["WCC"],
  photoSequence: [],
}
